### ISSUE TITLE
Remove Plotly plot after user removes clinical feature from select box

### ISSUE THREAD

**Issue by ZhenghaoZhu** [web4bio/webgen#129]
The plot when selecting a clinical feature doesn't disappear after the clinical feature is removed from the select box.

**Comment by ZhenghaoZhu** [comment]
Fixed

**Comment by enemeth19** [comment]
I don't think this was fixed

**Comment by ZhenghaoZhu** [comment]
Yea must've confused this with another issue.

**Comment by enemeth19** [comment]
I just realized that this is a repeat issue. See Issue #120
