### ISSUE TITLE
Resize violin plots

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#138]
If only displaying a small number of violins, the plot should be made smaller (i.e., not take up the width of the whole webpage)

**Comment by 19aanand** [comment]
We need to do the following:

1. Have the violin plots not take up the entire width of the screen
2. Reduce the amount of whitespace in between violin curves
3. Make sure faceting does not ruin the stylistic look

**Comment by 19aanand** [comment]
New dimensions should be the following:
- Width is 50% of what it is now
- Height is 75% of what it is now

**Comment by 19aanand** [comment]
Pushed changes to reflect this in _resizeViolins_ branch. The margins between plots may need to be updated though.

**Comment by enemeth19** [comment]
Ready to merge to dev?

**Comment by 19aanand** [comment]
Almost! The margins between the plots need to be slightly tweaked.

**Comment by 19aanand** [comment]
Based on Thursday's meeting, the margins between the plots are good. This branch will be merged to dev.
