### ISSUE TITLE
Change chart type for fields with continuous data

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#176]
- i.e., Replace pie chart with a different graph type (e.g., histogram)
- Use Plotly.js

**Comment by cgbrem** [comment]
Pushed code to 'continuousDataChart' branch for creating histograms only for continuous data and pie charts for categorical data, but I still have to implement selecting/deselecting bars in the chart. Currently, the list of continuous clinical features is hardcoded in the createPieCharts.js file.

**Comment by enemeth19** [comment]
I am going to create a pull request since the subject of this issue has already been addressed. We can make more specific issues pertaining to the histograms next.
