### ISSUE TITLE
Selections in gene 1 select box and gene 2 select box are linked

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#183]

**Comment by enemeth19** [comment]
Selected options in gene 2 select box do not populate in gene 2's local storage object

**Comment by enemeth19** [comment]
Rather, selected options in gene 2 select box are appended to gene 1's local storage object

**Comment by enemeth19** [comment]
@ZhenghaoZhu Do you know why this is happening with Local Storage?

**Comment by ZhenghaoZhu** [comment]
What branch should I look at?

**Comment by enemeth19** [comment]
updateCohortSelection

**Comment by ZhenghaoZhu** [comment]
@enemeth19 So I fixed it, basically, the boxes had the same "id" for all the options, and that caused the bug. I just added a "_" at the end of geneTwo select box ids to fix it.

**Comment by enemeth19** [comment]
@ZhenghaoZhu Awesome! Thank you!!
