### ISSUE TITLE
Add pathway selection

### ISSUE THREAD

**Issue by 19aanand** [web4bio/webgen#207]
User should be able to select a pathway and have a corresponding set of genes be queried.

**Comment by 19aanand** [comment]
Branch name is preselectedGenes

**Comment by amaraim22** [comment]
Can you please commit those changes you made to this branch too?

**Comment by ZhenghaoZhu** [comment]
Can I take this issue?

**Comment by amaraim22** [comment]
> Can I help with this issue?

Yes, of course!

**Comment by 19aanand** [comment]
The select box is now in line with the second gene select box. I also believe @prvshenoy01 wanted to be added as an assignee to this issue.

**Comment by ZhenghaoZhu** [comment]
Just pushed some changes and wrote out the next steps in fillSelectBoxes.js, give it a try whenever you have the time.
