### ISSUE TITLE
"days_to_death" clinical feature should be displayed as KM plot

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#241]

**Comment by kevin-murgas** [comment]
Also need to use "days_to_last_followup" and "vital_status" in Kaplan Meier curves (for right censoring)

**Comment by enemeth19** [comment]
After discussion, it seems appropriate to create KM plots as a new feature in a new tab (alongside heatmap and violin plots). However, we will most likely put this issue on hold for now, as we are working to resolve bugs in preparation for a new release.
