### ISSUE TITLE
Heatmap and violin plots do not load if no clinical features are selected

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#250]

**Comment by enemeth19** [comment]
@kevin-murgas I think this is because buildHeatmap() requires a clinicalData argument. If no clinical features are selected from the dropdown, then (clinicalData == undefined) evaluates to TRUE. We need to be able to handle this condition.

**Comment by kevin-murgas** [comment]
Not sure if the fix I recently implemented (in heatmap pull request) which queries all clinical features regardless of selection will fix this problem. There is still the case in which no barcodes are selected (if no intersection), that would probably cause an error still.
