### ISSUE TITLE
Gene mutation pie charts "flinch" when a new pie chart is added

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#251]

**Comment by ericr491** [comment]
Update:
The most recent commits in the updateImage branch should fix this issue, I'm waiting for Purva's changes to be merged, b/c I think there will be merge conflicts to resolve / it might break my changes. So I probably won't create a pull request at least not right now.

**Comment by enemeth19** [comment]
@ericr491 Thanks for the update! We have merged Purva's changes into development, so please let us know if you are still interested in resolving this issue.
