### ISSUE TITLE
Improve load time for options in tumor type dropdown

### ISSUE THREAD

**Issue by enemeth19** [web4bio/webgen#274]

**Comment by enemeth19** [comment]
Try loading tumor types on page load, rather than on click of dropdown box

**Comment by enemeth19** [comment]
Try to optimize [this function's](https://github.com/web4bio/webgen/blob/71aa9b278c5b5ffd093edbe54a5e84850205e70d/main/js/fillSelectBoxes.js#L26) performance

**Comment by rmoffitt** [comment]
Issue seems to have resolved. Leaving the issue open for another week or so.
