### ISSUE TITLE
add custom html element for dimensional charting

### ISSUE THREAD

**Issue by kaczmarj** [web4bio/webgen#283]
we would like to have a convenient way of creating dimensional charting plots. we can create a custom element that does this, and this element can consume a JSON document.

i will try to take this on, but of course anyone can participate.

some references:
- [mozilla documentation on custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements)
- [dc.js library](https://dc-js.github.io/dc.js/) -- we can use this under the hood
- [plotly example of custom html elements](https://episphere.github.io/plotly/)

one idea for the name of the custom element is `<dimensional-chart>`.

**Comment by 19aanand** [comment]
Below is a great video that shows a simple example of making a custom HTML element and gives a good introduction to the Shadow DOM.
[https://www.youtube.com/watch?v=_Tr9ZcXcMjQ](url)

**Comment by kaczmarj** [comment]
on the main page, we have checkboxes and two plots. the plots exist in two different tabs. it would be nice for checkboxes to be conserved in the two panels. we want to take inspiration from `dc.js` to "listen"  between the tabs.
