### ISSUE TITLE
question about this project's branches

### ISSUE THREAD

**Issue by kaczmarj** [web4bio/webgen#296]
could someone explain the purpose of the master and release branches? which branch is used for https://web4bio.github.io/webgen/main/html/ ?

**Comment by enemeth19** [comment]
Hi @kaczmarj ! The **release** branch is updated when there is a working version of the app with a collection of new features. This is the branch that is reflected in our GitHub Pages at [https://web4bio.github.io/webgen/main/html/](https://web4bio.github.io/webgen/main/html/). The **master** branch is updated with changes to README.md, but, outside of that, it is updated less often, with the idea of updating it when we are ready to publish a version of the app. Interested in hearing your comments on this though, as our workflow has evolved over the past couple of years.

**Comment by kaczmarj** [comment]
thanks @enemeth19 - that's helpful. there's some redundancy between master and release, but that's not really a problem. i'll close this now.
