### ISSUE TITLE
BUG: Uncaught (in promise) TypeError: x[currentFeature] is undefined

### ISSUE THREAD

**Issue by kaczmarj** [web4bio/webgen#309]
when I select `(COAD) Colon adenocarcinoma` for the tumor type and then click outside of the selection box (ie anywhere on the page), I get the error below:

```
Uncaught (in promise) TypeError: x[currentFeature] is undefined
    continuousMap http://0.0.0.0:8000/js/fillSelectBoxes.js:320
    checkIfClinicalFeatureArrayIsNumeric http://0.0.0.0:8000/js/fillSelectBoxes.js:320
    fillClinicalSelectBox http://0.0.0.0:8000/js/fillSelectBoxes.js:329
    onchange http://0.0.0.0:8000/html/:1
    jQuery 5
    triggerChange https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:21
    onSelect https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:22
    selectHighlighted https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:22
    init https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:21
    bind https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:21
    jQuery 8
    init https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:21
    select2 https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:23
    jQuery 2
    select2 https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.4/select2.min.js:23
    <anonymous> http://0.0.0.0:8000/html/:102
    jQuery 13
fillSelectBoxes.js:320:52
```

**Comment by kaczmarj** [comment]
the same error happens for `(STES) stomach and esophageal carcinoma`. if i find this issue with other tumor types, i'll update this comment.

**Comment by enemeth19** [comment]
Hm, I can't replicate this error in the current state of the development branch

**Comment by enemeth19** [comment]
I believe that this happens because, for some clinical features in these tumor types that you have mentioned, there are undefined values. It seems that we do not handle these undefined values in our code, which results in this error in the console, as well as pie charts not being generated for those clinical features which may contain at least one undefined value.

**Comment by enemeth19** [comment]
This should be resolved with [Pull Request 318](https://github.com/web4bio/webgen/pull/318)

**Comment by enemeth19** [comment]
Seems to no longer be an issue
