### ISSUE TITLE
Incorrect number of samples displayed

### ISSUE THREAD

**Issue by spencerkrichevsky** [web4bio/webgen#319]
e.g., BRCA looks ok (n=1093)

![BMI530_Webgen_BRCA](https://user-images.githubusercontent.com/76532559/136450603-b085caed-af42-41f8-b704-8c14cc5c330a.JPG)

BRCA still looks ok (n=1093) and COAD looks ok (n=457)

![BMI530_Webgen_BRCA+COAD](https://user-images.githubusercontent.com/76532559/136451239-bab566ea-2d38-482f-9bc2-d0b25e4d7787.JPG)

BRCA still looks ok (n=1093) but COAD (n=457) and CHOL (n=36) displayed values are swapped

![BMI530_Webgen_BRCA+COAD+CHOL](https://user-images.githubusercontent.com/76532559/136451335-d27944a0-2f71-43b3-9743-155823dee338.JPG)

**Comment by enemeth19** [comment]
This inaccuracy occurs when tumor types are not selected by user in alphabetical order. See linked pull request
