### ISSUE TITLE
Move clinical/gene checkbox to the left

### ISSUE THREAD

**Issue by rmoffitt** [web4bio/webgen#336]
![issue](https://user-images.githubusercontent.com/12475201/138486525-efee3046-298f-4932-91fb-88a81570409e.png)

**Comment by kaczmarj** [comment]
in our webgen meeting on october 29, we decided to put the checkboxes on the left. because we are using the materialize framework, we can use their grid feature (see https://materializecss.com/grid.html#grid-responsive). an example code that comes from there website and broadly does what we want...

```html
    <div class="row">

      <div class="col s12 m4 l3">
        <!-- Checkboxes
              This content will be:
          3-columns-wide on large screens,
          4-columns-wide on medium screens,
          12-columns-wide on small screens  -->
      </div>

      <div class="col s12 m8 l9">
        <!-- Plots
              This content will be:
          9-columns-wide on large screens,
          8-columns-wide on medium screens,
          12-columns-wide on small screens  -->
      </div>

    </div>
```
