### ISSUE TITLE
thoughts on a common place to keep state of the app?

### ISSUE THREAD

**Issue by kaczmarj** [web4bio/webgen#353]
there are some stateful global variables in the app, and i get confused when trying to trace where some data comes from and where variables are defined or modified. one example of this is the variable `allClinicalData`. This is defined in `fillSelectBoxes.js` without an initial value, and it is referenced in multiple files, including `index.html`, `createPieCharts.js`, and `getDataFromSelectedPieSectors.js`.

when i say stateful, i mean a value that holds some information about the current usage of the app. things in local storage would also fall under the category of "state".

i think a great way to organize the code would be to separate stateful things from stateless things. i imagine that we could have one file (eg `state.js`) that contains the stateful variables, like `allClinicalData`. and we could make it a module, so we could use it like `state.allClinicalData` for example. that will make it clear where the variables are coming from and that they are stateful.

what do people think about this idea?

**Comment by 19aanand** [comment]
Closed with PR 371
