### ISSUE TITLE
update url to gene pathway list json file

### ISSUE THREAD

**Issue by kaczmarj** [web4bio/webgen#364]
from #363 

>NOTE: The URL in the fetch command needs to be updated to use the github.io link instead of the current method

```javascript
let getValidPathwaysList = async function () {
  //Note the specification of the 'preselectedGenes' branch name.
  //genePathwaysList.json needs to be uploaded to the branch running on the github.io link
  let validPathwaysList = await fetch(
    "https://raw.githubusercontent.com/web4bio/webgen/development/main/genePathwaysList.json"
  ).then((response) => response.json());
  validPathwaysList = Object.keys(validPathwaysList);
  localStorage.setItem("genePathways", validPathwaysList);
  return await validPathwaysList;
};
```

**Comment by enemeth19** [comment]
> to use the github.io link

Which link is this?

**Comment by kaczmarj** [comment]
https://web4bio.github.io/webgen/main/genePathwaysList.json

This ensures that webgen is using the same version of the file as the version of the app. Because the app uses the master branch, but currently this json is pulled from the develop branch. 

Best,
Jakub

**Comment by enemeth19** [comment]
Great - I understand. Thank you!
