### ISSUE TITLE
make slides about app state for december 3 2021

### ISSUE THREAD

**Issue by kaczmarj** [web4bio/webgen#366]
for december 3 2021, we should make some slides that outline our thoughts about the app state. feel free to add to the todo below

- [x] what do we want to store in the state
- [x] in which functions is the state used
- [x] how can we represent the state (eg what might a state object look like)

**Comment by kaczmarj** [comment]
@jmath908 @ericr491 @liwll - can you please post your ideas for this here? we will present these ideas on friday dec 3 2021

**Comment by jmath908** [comment]
I can do the first box- "_what do we want to store in the state_"
for this, we can consider data stored in select boxes:
1. tumor type
2. gene mutation
3. metadata
4. cohort - gene + pathways

**Comment by jmath908** [comment]
https://docs.google.com/presentation/d/1J1FB8-UlgsUbvOkDTgO5HoEQAuC6PJHI49rgx-9FPZ4/edit#slide=id.p
you will have to use your sbu email

**Comment by kaczmarj** [comment]
slides are done -- thanks all
